import Head from "next/head";
import { useEffect } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebase";

export default function Home() {
  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        window.location.href = "/homepage";
      } else {
        window.location.href = "/login";
      }
    });
  }, []);

  return (
    <div>
      <Head>
        <title>IITGN GR Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

// const Nav = styled.nav`
//   display: flex;
//   flex-direction: horizontal;
//   height: 20px;
//   border-bottom: 5px solid #e5e5e5;
//   padding-bottom: 30px;
// `;
