import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>IITGN GR Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

// const Nav = styled.nav`
//   display: flex;
//   flex-direction: horizontal;
//   height: 20px;
//   border-bottom: 5px solid #e5e5e5;
//   padding-bottom: 30px;
// `;
